name: Old Is Gold Build

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
        
    - name: Install Stable Libraries
      run: |
        python -m pip install --upgrade pip
        # Hum specific purana version use karenge jo 100% stable hai
        pip install moviepy==1.0.3 imageio==2.9.0 imageio-ffmpeg numpy==1.23.5 opencv-python decorator==4.4.2
        pip install pyinstaller
        
    - name: Build EXE
      run: |
        # Ab humein metadata copy karne ki zaroorat nahi padegi
        pyinstaller --onefile --name="VideoBypass_Final" main.py --hidden-import=moviepy --hidden-import=imageio --hidden-import=imageio_ffmpeg
        
    - name: Upload EXE
      uses: actions/upload-artifact@v4
      with:
        name: Download_Me_Now
        path: dist/VideoBypass_Final.exe
